version: 1.0
provider:
  name: openfaas
  gateway: http://172.169.8.168:31112
functions:
#  pycon:
#    lang: python3
#    handler: ./pycon
#    image: tinker.siat.ac.cn/tinker/pycon-tk:latest


  MultinomialNB-general: 
    lang: python3
    handler: ./MultinomialNB-general    
    image: tinker.siat.ac.cn/openfaas-fn/MultinomialNB-general:1.0.0