version: 1.0
provider:
  name: openfaas
  gateway: http://172.169.8.168:31112
functions:
#  pycon:
#    lang: python3
#    handler: ./pycon
#    image: tinker.siat.ac.cn/tinker/pycon-tk:latest


  facerecognition: 
    lang: python3-debian
    handler: ./FaceRecognition    
    image: tinker.siat.ac.cn/openfaas-fn/facerecognition:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  multinomialnb: 
    lang: python3-debian
    handler: ./MultinomialNB   
    image: tinker.siat.ac.cn/openfaas-fn/multinomialnb-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  passiveaggressiveclassifier: 
    lang: python3-debian
    handler: ./PassiveAggressiveClassifier   
    image: tinker.siat.ac.cn/openfaas-fn/passiveaggressiveclassifier-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  perceptron: 
    lang: python3-debian
    handler: ./Perceptron  
    image: tinker.siat.ac.cn/openfaas-fn/perceptron-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  randomforestregressor: 
    lang: python3-debian
    handler: ./RandomForestRegressor  
    image: tinker.siat.ac.cn/openfaas-fn/randomforestregressor-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  sgdclassifier: 
    lang: python3-debian
    handler: ./SGDClassifier   
    image: tinker.siat.ac.cn/openfaas-fn/sgdclassifier-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  sgdregressor: 
    lang: python3-debian
    handler: ./SGDRegressor 
    image: tinker.siat.ac.cn/openfaas-fn/sgdregressor-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model

  svr: 
    lang: python3-debian
    handler: ./SVR
    image: tinker.siat.ac.cn/openfaas-fn/svr-general:1.0.0
    configuration: 
     copy:
      - ./data
      - ./model
